# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: seokang <seokang@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/11 15:27:07 by seokang           #+#    #+#              #
#    Updated: 2022/07/19 17:32:45 by seokang          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
CFLAGS = -Wall -Wextra -Werror
NAME = libft.a
HEADER = libft.h

SRCS = 	ft_isalpha.c \
		ft_isdigit.c \
		ft_isalnum.c \
		ft_isascii.c \
	   	ft_isprint.c \
	   	ft_strlen.c \
	   	ft_toupper.c \
	   	ft_tolower.c \
	   	ft_strchr.c \
	   	ft_strrchr.c \
		ft_memset.c \
		ft_memcmp.c \
		ft_strncmp.c \
		ft_strnstr.c \
		ft_bzero.c \
		ft_memcpy.c \
		ft_memmove.c \
		ft_memchr.c \
		ft_strlcpy.c \
		ft_strlcat.c \
		ft_atoi.c \
		ft_calloc.c \
		ft_strdup.c
OBJS = $(SRCS:.c=.o)

ifdef BONUSFLAG
	ALLOBJS 	= $(OBJS) $(OBJS_BONUS)
else
	ALLOBJS 	= $(OBJS)
endif

all: $(NAME)

$(NAME) : $(OBJS)
	ar rcs $(NAME) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@ -I $(HEADER)

bonus:
	make BONUSFLAG=1
	
clean:
	rm -rf $(OBJS)

fclean: clean
	rm -rf $(NAME)

re: fclean all

.PHONY: all bonus clean fclean re
